platform :ios, '10.0'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
use_frameworks!
permissions_path = '../node_modules/react-native-permissions/ios'

 pre_install do |installer|
   installer.pod_targets.each do |pod|
     if pod.name.eql?('RNPermissions') || pod.name.start_with?('Permission-')
       def pod.build_type;
         Pod::BuildType.static_library # I assume you use CocoaPods >= 1.9
       end
     end
   end
 end

target 'sample_app' do
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])
  pod 'NearBee'
  pod 'RNNearBee', :path => '../node_modules/react-native-nearbee'
  pod 'Permission-BluetoothPeripheral', :path => "#{permissions_path}/BluetoothPeripheral.podspec"
  pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways.podspec"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse.podspec"
  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications.podspec"

end

